controller_manager:
  ros__parameters:
    update_rate: 20

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

spider_leg_back_left_controller:
  ros__parameters:
    type: forward_command_controller/ForwardCommandController
    joints:
      - hip_backleft
      - leg_backleft
      - foot_backleft
    interface_name: position

spider_leg_back_right_controller:
  ros__parameters:
    type: forward_command_controller/ForwardCommandController
    joints:
      - hip_backright
      - leg_backright
      - foot_backright
    interface_name: position

spider_leg_front_left_controller:
  ros__parameters:
    type: forward_command_controller/ForwardCommandController
    joints:
      - hip_frontleft
      - leg_frontleft
      - foot_frontleft
    interface_name: position

spider_leg_front_right_controller:
  ros__parameters:
    type: forward_command_controller/ForwardCommandController
    joints:
      - hip_frontright
      - leg_frontright
      - foot_frontright
    interface_name: position

spider_dome_controller:
  ros__parameters:
    type: forward_command_controller/ForwardCommandController
    joints:
      - base_to_cupula
    interface_name: position

# spider_controller:
#   ros__parameters:
#     type: forward_command_controller/ForwardCommandController
#     joints:
#       - base_to_cupula
#       - hip_backright
#       - hip_backleft
#       - hip_frontright
#       - hip_frontleft
#       - leg_backright
#       - leg_backleft
#       - leg_frontright
#       - leg_frontleft
#       - foot_frontleft
#       - foot_frontright
#       - foot_backright
#       - foot_backleft
#     interface_name: position